export const employees = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    position: 'Manager',
    phone: '555-555-5555',
    email: 'johndoe@x.com',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    position: 'Developer',
    phone: '555-555-5556',
    email: 'janesmith@x.com',
  },
  {
    id: 3,
    firstName: 'Michael',
    lastName: 'Johnson',
    position: 'Designer',
    phone: '555-555-5557',
    email: 'michaeljohnson@x.com',
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Davis',
    position: 'Product Manager',
    phone: '555-555-5558',
    email: 'emilydavis@x.com',
  },
  {
    id: 5,
    firstName: 'James',
    lastName: 'Brown',
    position: 'QA Engineer',
    phone: '555-555-5559',
    email: 'jamesbrown@x.com',
  },
  {
    id: 6,
    firstName: 'Olivia',
    lastName: 'Wilson',
    position: 'HR Specialist',
    phone: '555-555-5560',
    email: 'oliviawilson@x.com',
  },
  {
    id: 7,
    firstName: 'Daniel',
    lastName: 'Martinez',
    position: 'Data Analyst',
    phone: '555-555-5561',
    email: 'danielmartinez@x.com',
  },
  {
    id: 8,
    firstName: 'Sophia',
    lastName: 'Anderson',
    position: 'Marketing Coordinator',
    phone: '555-555-5562',
    email: 'sophiaanderson@x.com',
  },
  {
    id: 9,
    firstName: 'David',
    lastName: 'Taylor',
    position: 'Customer Support',
    phone: '555-555-5563',
    email: 'davidtaylor@x.com',
  },
  {
    id: 10,
    firstName: 'Mia',
    lastName: 'Thomas',
    position: 'Sales Representative',
    phone: '555-555-5564',
    email: 'miathomas@x.com',
  },
  {
    id: 11,
    firstName: 'Christopher',
    lastName: 'Lee',
    position: 'Business Analyst',
    phone: '555-555-5565',
    email: 'christopherlee@x.com',
  },
  {
    id: 12,
    firstName: 'Grace',
    lastName: 'Harris',
    position: 'Operations Manager',
    phone: '555-555-5566',
    email: 'graceharris@x.com',
  },
  {
    id: 13,
    firstName: 'Andrew',
    lastName: 'Clark',
    position: 'Finance Manager',
    phone: '555-555-5567',
    email: 'andrewclark@x.com',
  },
  {
    id: 14,
    firstName: 'Lily',
    lastName: 'Lewis',
    position: 'Content Writer',
    phone: '555-555-5568',
    email: 'lilylewis@x.com',
  },
  {
    id: 15,
    firstName: 'Ethan',
    lastName: 'Walker',
    position: 'UI/UX Designer',
    phone: '555-555-5569',
    email: 'ethanwalker@x.com',
  },
  {
    id: 16,
    firstName: 'Ava',
    lastName: 'Allen',
    position: 'Software Engineer',
    phone: '555-555-5570',
    email: 'avaallen@x.com',
  },
  {
    id: 17,
    firstName: 'Matthew',
    lastName: 'Young',
    position: 'IT Specialist',
    phone: '555-555-5571',
    email: 'matthewyoung@x.com',
  },
  {
    id: 18,
    firstName: 'Ella',
    lastName: 'King',
    position: 'Recruiter',
    phone: '555-555-5572',
    email: 'ellaking@x.com',
  },
  {
    id: 19,
    firstName: 'Benjamin',
    lastName: 'Wright',
    position: 'DevOps Engineer',
    phone: '555-555-5573',
    email: 'benjaminwright@x.com',
  },
  {
    id: 20,
    firstName: 'Harper',
    lastName: 'Scott',
    position: 'Project Coordinator',
    phone: '555-555-5574',
    email: 'harperscott@x.com',
  },
  {
    id: 21,
    firstName: 'William',
    lastName: 'Green',
    position: 'Accountant',
    phone: '555-555-5575',
    email: 'williamgreen@x.com',
  },
];
